name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential
          sudo apt install cmake
          sudo apt install libcairo2-dev
          sudo apt install libgraphicsmagick1-dev
          sudo apt install libpng-dev
          git clone --recurse-submodules https://github.com/cpp-io2d/P0267_RefImpl
          cd P0267_RefImpl
          mkdir Debug
          cd Debug
          cmake ..
          cmake --build .
          sudo make install
      - name: Build project with cmake
        run: |
          cd ..
          cd ..
          mkdir build && cd build
          cmake ..
          make
      - name: Run tests
        run: |
          ./test