name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install dependencies
        run: |
          sudo apt install libcairo2-dev
          sudo apt install libgraphicsmagick1-dev
          sudo apt install libpng-dev
          cd ..
          git clone --recurse-submodules https://github.com/cpp-io2d/P0267_RefImpl
          cd P0267_RefImpl
          mkdir Debug
          cd Debug
          cmake --build .
          sudo make install .
          cd ..
          cd ..
          cd RoutePlanner
      - name: Build project with cmake
        uses: nicledomaS/cmake_build_action@v1.4
        with:
          submodule_update: ON
          run_tests: ON
          unit_test_build: -Dtest=ON