name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build base image
        run: |
          docker build --target=base --tag project:base -f ci/docker/ubuntu/Dockerfile .
      - name: Build project with cmake and test.
        run: |
          docker run -v $(pwd):/usr/src/project --rm --init -t --name test project:base 
          docker exec -it test /bin/bash -c "cd /usr/src/project && mkdir build && cmake .. && make && ./test"