name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build base image
        run: |
          docker build -t project-dev -f ci/docker/ubuntu/Dockerfile .
      - name: Build project with cmake and test.
        run: |
          docker run --rm -d -v $(pwd):/usr/src/project -ti project-dev bash --name test
          docker exec -it test bash -c "cd /usr/src/project && rm -rf build && mkdir build && cd build && cmake .. && make && ./test"